const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),menu=document.querySelector('#menu');
const bgNames=['bg1.png','bg2.png','bg3.png'],charNames=['pipo.png','lumi.png','bumbo.png','tiki.png','mimi.png'];
const load=n=>{const i=new Image;i.src='assets/'+n;return i},bgs=bgNames.map(load),chars=charNames.map(load);
let running=false,paused=false,last=0,score=0,combo=0,lives=7,phase=1,elapsed=0,mibis=[],particles=[],pointer={x:-999,y:-999};
const rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0)}
function spawn(i=mibis.length%5){const w=canvas.clientWidth,h=canvas.clientHeight;return{x:rnd(90,w-90),y:rnd(145,h-75),vx:rnd(-1,1)*110,vy:rnd(-1,1)*90,r:Math.max(38,Math.min(w,h)*.065),img:chars[i],shield:Math.random()<.24?1:0,alive:1,flash:0}}
function reset(){score=0;combo=0;lives=7;phase=1;elapsed=0;particles=[];mibis=Array.from({length:5},(_,i)=>spawn(i));running=true;paused=false;menu.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function update(dt){elapsed+=dt;const next=Math.min(10,1+Math.floor(elapsed/25));if(next!==phase){phase=next;lives=7;mibis.forEach((m,i)=>{if(i%2===phase%2)m.shield=1});while(mibis.length<Math.min(10,5+Math.floor(phase/2)))mibis.push(spawn())}const w=canvas.clientWidth,h=canvas.clientHeight;for(const m of mibis){if(!m.alive)continue;const d=dist(m,pointer);if(d<170){const ax=(m.x-pointer.x)/(d||1),ay=(m.y-pointer.y)/(d||1);m.vx+=ax*210*dt;m.vy+=ay*210*dt}m.vx+=Math.sin(elapsed+m.y)*8*dt;m.vy+=Math.cos(elapsed*.8+m.x)*8*dt;const max=120+phase*15,s=Math.hypot(m.vx,m.vy)||1;if(s>max){m.vx=m.vx/s*max;m.vy=m.vy/s*max}m.x+=m.vx*dt;m.y+=m.vy*dt;if(m.x<m.r||m.x>w-m.r)m.vx*=-1;if(m.y<125+m.r*.3||m.y>h-m.r)m.vy*=-1;m.x=Math.max(m.r,Math.min(w-m.r,m.x));m.y=Math.max(125+m.r*.3,Math.min(h-m.r,m.y));m.flash=Math.max(0,m.flash-dt)}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,bg=bgs[Math.min(2,Math.floor((phase-1)/3))];ctx.clearRect(0,0,w,h);if(bg.complete){ctx.drawImage(bg,0,0,w,h)}else{ctx.fillStyle='#06355c';ctx.fillRect(0,0,w,h)}ctx.fillStyle='#030b1ce8';ctx.fillRect(14,14,Math.min(620,w-90),92);ctx.strokeStyle='#42efff';ctx.lineWidth=2;ctx.strokeRect(14,14,Math.min(620,w-90),92);ctx.font='800 14px system-ui';ctx.fillStyle='#ff55dc';ctx.fillText('SCORE',32,40);ctx.fillText('VIDAS',220,40);ctx.fillText('EVOLUÇÃO',390,40);ctx.font='900 29px system-ui';ctx.fillStyle='#5bf4ff';ctx.fillText(String(score).padStart(7,'0'),32,77);ctx.fillStyle='#ffe62f';ctx.font='24px system-ui';ctx.fillText('♥'.repeat(lives),220,78);ctx.fillStyle='#fff';ctx.font='900 24px system-ui';ctx.fillText('FASE '+String(phase).padStart(2,'0'),390,77);for(const m of mibis){if(!m.alive)continue;ctx.save();ctx.translate(m.x,m.y);if(m.vx<0)ctx.scale(-1,1);if(m.shield){ctx.beginPath();ctx.arc(0,0,m.r*.82,0,Math.PI*2);ctx.fillStyle='#55eaff22';ctx.fill();ctx.strokeStyle='#8ff6ff';ctx.lineWidth=4;ctx.stroke()}if(m.flash)ctx.globalAlpha=.4;ctx.drawImage(m.img,-m.r,-m.r,m.r*2,m.r*2);ctx.restore()}for(const p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,5,5)}ctx.globalAlpha=1;if(combo>1){ctx.fillStyle='#fff';ctx.font='900 22px system-ui';ctx.fillText('COMBO x'+combo,30,h-28)}}
function loop(t){if(!running)return;const dt=Math.min(.035,(t-last)/1000);last=t;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
function hit(x,y){if(!running||paused)return;pointer={x,y};let target=[...mibis].sort((a,b)=>dist(a,pointer)-dist(b,pointer))[0];if(target&&dist(target,pointer)<target.r*.78){if(target.shield){target.shield=0;score+=25*phase}else{combo++;score+=100*phase*Math.min(8,1+Math.floor(combo/4));for(let i=0;i<25;i++)particles.push({x:target.x,y:target.y,vx:rnd(-220,220),vy:rnd(-220,220),life:rnd(.3,.8),c:i%2?'#55efff':'#ff5bdb'});Object.assign(target,spawn(Math.floor(Math.random()*5)))}}else{combo=0;lives--;if(lives<=0){running=false;menu.querySelector('h1').textContent='FIM DE JOGO';menu.querySelector('p').textContent='Pontuação: '+score+' · Fase: '+phase+'. Os Mibis aprenderam com seus movimentos. Tente novamente!';menu.querySelector('button').textContent='JOGAR NOVAMENTE';menu.classList.remove('hidden')}}}
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer={x:e.clientX-r.left,y:e.clientY-r.top}});canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();hit(e.clientX-r.left,e.clientY-r.top)});document.querySelector('#start').onclick=reset;document.querySelector('#pause').onclick=()=>paused=!paused;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='p')paused=!paused});new ResizeObserver(resize).observe(canvas);document.querySelector('#pix').onclick=async e=>{try{await navigator.clipboard.writeText('17909502877');e.target.textContent='Chave Pix copiada!'}catch{prompt('Copie a chave Pix:','17909502877')}};
